/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextPane;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author albertovenegas
 */
public class audit extends javax.swing.JFrame {
    
    conexion con = new conexion();
    Connection cn = con.conexion();
    static String empresa;
    static String categoria;

    /**
     * Creates new form basico
     */
    public audit() {
        initComponents();
        if (main.empresa2 != null && !main.empresa2.isEmpty()) {
            fieldEmpresa.setText(main.empresa2);
            empresa = main.empresa2;
            fieldEmpresa.setEditable(false);
        }
        if (categorias.categoria != null && !categorias.categoria.isEmpty()){
            fieldCategoria.setText(categorias.categoria);
            categoria = categorias.categoria;
        }
        if (main.categoriaM != null && !main.categoriaM.isEmpty()){
            fieldCategoria.setText(main.categoriaM);
            categoria = main.categoriaM;
        }
    }
    public void close(){
        WindowEvent closeWindow = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVolver = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelEmpresa = new javax.swing.JLabel();
        labelAuditor = new javax.swing.JLabel();
        labelDescripcion = new javax.swing.JLabel();
        fieldEmpresa = new javax.swing.JTextField();
        fieldAuditor = new javax.swing.JTextField();
        guardar = new javax.swing.JButton();
        labelID = new javax.swing.JLabel();
        fieldID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        fieldDescripcion = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        fieldCategoria = new javax.swing.JTextField();
        btnGuia = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        articulosENS = new javax.swing.JMenu();
        articulosENS2 = new javax.swing.JMenuItem();
        anexosENS = new javax.swing.JMenu();
        marcoOrganizativo = new javax.swing.JMenuItem();
        marcoOperacional = new javax.swing.JMenuItem();
        medidasProteccion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(30, 160, 250));

        titulo.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Auditoría de cumplimiento del ENS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información general", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 14))); // NOI18N

        labelEmpresa.setText("Nombre");

        labelAuditor.setText("Auditor");

        labelDescripcion.setText("Descripción");

        fieldEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldEmpresaActionPerformed(evt);
            }
        });

        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        labelID.setText("Id Auditoría");

        fieldDescripcion.setColumns(20);
        fieldDescripcion.setRows(5);
        jScrollPane1.setViewportView(fieldDescripcion);

        jLabel1.setText("Categoría");

        fieldCategoria.setEditable(false);
        fieldCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCategoriaActionPerformed(evt);
            }
        });

        btnGuia.setText("Guía de uso");
        btnGuia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(fieldCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(labelID)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(fieldID))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(labelEmpresa)
                                    .addGap(27, 27, 27)
                                    .addComponent(fieldEmpresa))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(labelAuditor)
                                    .addGap(33, 33, 33)
                                    .addComponent(fieldAuditor, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(labelDescripcion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(guardar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnGuia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmpresa)
                    .addComponent(fieldEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAuditor)
                    .addComponent(fieldAuditor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelID)
                    .addComponent(fieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fieldCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(labelDescripcion)
                                .addGap(45, 45, 45))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnGuia, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(guardar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        articulosENS.setText("Cumplimiento artículos ENS");

        articulosENS2.setText("Artículos ENS");
        articulosENS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                articulosENS2ActionPerformed(evt);
            }
        });
        articulosENS.add(articulosENS2);

        jMenuBar1.add(articulosENS);

        anexosENS.setText("Cumplimiento medidas anexos ENS");

        marcoOrganizativo.setText("Marco organizativo");
        marcoOrganizativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcoOrganizativoActionPerformed(evt);
            }
        });
        anexosENS.add(marcoOrganizativo);

        marcoOperacional.setText("Marco operacional");
        marcoOperacional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcoOperacionalActionPerformed(evt);
            }
        });
        anexosENS.add(marcoOperacional);

        medidasProteccion.setText("Medidas de protección");
        medidasProteccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medidasProteccionActionPerformed(evt);
            }
        });
        anexosENS.add(medidasProteccion);

        jMenuBar1.add(anexosENS);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addGap(14, 14, 14))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        
        main n = new main();
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void fieldEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldEmpresaActionPerformed

    private void marcoOperacionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcoOperacionalActionPerformed
        //empresa = main.empresa2;
        if (empresa != null && !empresa.isEmpty()) {
            if (categoria.equalsIgnoreCase("Baja")){
                marcoOperacional operacional = new marcoOperacional();
                operacional.setVisible(true);
            }
            else if(categoria.equalsIgnoreCase("Media")){
                marcoOperacionalMedio operacional2 = new marcoOperacionalMedio();
                operacional2.setVisible(true);
            }
            else if(categoria.equalsIgnoreCase("Alta")){
                marcoOperacionalAlta operacional3 = new marcoOperacionalAlta();
                operacional3.setVisible(true);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Introduzca los datos de la auditoría." );
        }
    }//GEN-LAST:event_marcoOperacionalActionPerformed

    private void medidasProteccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medidasProteccionActionPerformed
        //empresa = main.empresa2;
        if (empresa != null && !empresa.isEmpty()) {
            if (categoria.equalsIgnoreCase("Baja")){
                medidasProteccion proteccion = new medidasProteccion();
                proteccion.setVisible(true);
            }
            else if(categoria.equalsIgnoreCase("Media")){
                medidasProteccionMedio proteccionM = new medidasProteccionMedio();
                proteccionM.setVisible(true);
            }
            else if(categoria.equalsIgnoreCase("Alta")){
                medidasProteccionAlta proteccionA = new medidasProteccionAlta();
                proteccionA.setVisible(true);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Introduzca los datos de la auditoría." );
        }
    }//GEN-LAST:event_medidasProteccionActionPerformed

    private void articulosENS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_articulosENS2ActionPerformed
       // empresa = main.empresa2;
        if (empresa != null && !empresa.isEmpty()) {
            if (categoria.equalsIgnoreCase("Baja")){
                articulosENS l = new articulosENS();
                l.setVisible(true);
            }
            else if(categoria.equalsIgnoreCase("Media")){
                articulosENSMedio l2 = new articulosENSMedio();
                l2.setVisible(true);
            }
            else if(categoria.equalsIgnoreCase("Alta")){
                articulosENSAlta l3 = new articulosENSAlta();
                l3.setVisible(true);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Introduzca los datos de la auditoría." );
        }
    }//GEN-LAST:event_articulosENS2ActionPerformed

    private void marcoOrganizativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcoOrganizativoActionPerformed
        //empresa = main.empresa2;
        if (empresa != null && !empresa.isEmpty()) {
            if (categoria.equalsIgnoreCase("Baja")){
                marcoOrganizativo organizativo = new marcoOrganizativo();
                organizativo.setVisible(true);
            }else if(categoria.equalsIgnoreCase("Media")){
                marcoOrganizativoMedio organizativoM = new marcoOrganizativoMedio();
                organizativoM.setVisible(true);           
        }else if(categoria.equalsIgnoreCase("Alta")){
            marcoOrganizativoAlta organizativoA = new marcoOrganizativoAlta();
            organizativoA.setVisible(true);
        }
        }else{
            JOptionPane.showMessageDialog(null, "Introduzca los datos de la auditoría." );
        }
    }//GEN-LAST:event_marcoOrganizativoActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        Statement stmt =null;
        empresa = null;
        empresa = fieldEmpresa.getText();
        try {
            PreparedStatement pps = cn.prepareStatement("INSERT INTO Auditorias2(IdAuditorias,Nombre,Auditor,Categoria,Observaciones) VALUEs(?,?,?,?,?)");
                    String IdAuditorias = fieldID.getText();
                    String empresa = fieldEmpresa.getText();
                    String Auditor = fieldAuditor.getText();
                    String observaciones = fieldDescripcion.getText();
                    pps.setString(1, IdAuditorias);
                    pps.setString(2, empresa);
                    pps.setString(3, Auditor);
                    pps.setString(4, categoria);
                    pps.setString(5, observaciones);
                    pps.executeUpdate();
            
            stmt = cn.createStatement();
            String sql = "CREATE TABLE "+empresa+"( "+
                         "ArtAuditar varchar (40) primary key not null, " +
                         "Audita varchar (2), " +
                         "GradoMadurez varchar(2), " +
                         "Evidencias varchar(255), " +
                         "Observaciones varchar(255));";
            stmt.execute(sql);

            JOptionPane.showMessageDialog(null, "Se ha generado la BBDD de: " + empresa +"." );
       //Ejecutamos el Statement
            
        } catch (SQLException ex) {
            Logger.getLogger(audit.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "No se ha podido generar la BBDD. Nombre o ID ya utilizados.");
        }
    }//GEN-LAST:event_guardarActionPerformed

    private void btnGuiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuiaActionPerformed
        JTextPane textPane = new JTextPane();
        textPane.setEditable(false);
        StyledDocument doc = textPane.getStyledDocument();
        
        // Establecer estilos para el texto
        SimpleAttributeSet headingStyle = new SimpleAttributeSet();
        StyleConstants.setFontSize(headingStyle, 14);
        StyleConstants.setBold(headingStyle, true);
        
        SimpleAttributeSet listItemStyle = new SimpleAttributeSet();
        StyleConstants.setFontSize(listItemStyle, 12);
        StyleConstants.setFirstLineIndent(listItemStyle, 20);
        
        // Agregar contenido al documento
        try {
            doc.insertString(doc.getLength(), "Información que debe tener el cuenta el auditor:\n\n", headingStyle);
            doc.insertString(doc.getLength(), "- Si desea iniciar una nueva auditoría, introduzca datos para generar la BBDD, \n en caso contrario, ya están introducidos los datos y puede continuar.\n", listItemStyle);
            doc.insertString(doc.getLength(), "- El Grado de madurez indica el nivel de cumplimiento de la medida \n siendo L0 el mínimo y L5 el máximo.\n", listItemStyle);
            doc.insertString(doc.getLength(), "- En caso de encontrar una No Conformidad, indíquelo en el campo de Registros: Documentos,\n escribiendo No Conformidad.\n", listItemStyle);
           // doc.insertString(doc.getLength(), "- Punto 3\n", listItemStyle);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        JScrollPane scrollPane = new JScrollPane(textPane);
        
        JOptionPane.showMessageDialog(this, scrollPane, "Guía de uso", JOptionPane.INFORMATION_MESSAGE); 
//empresa = fieldEmpresa.getText();
        //conexion con = new conexion();
       // Connection cn = con.conexion();
       // PreparedStatement ps;
       // ResultSet rs;
       //try{
       //  ps = cn.prepareStatement("SELECT COUNT(*) as count FROM Auditorias WHERE Empresa = '" + empresa + "'");  
        // rs = ps.executeQuery();

         //   boolean exists = false;
          //  if (rs.next() && rs.getInt("count") > 0) {
           //     JOptionPane.showMessageDialog(null, "Puede continuar o visualir datos de su auditoría");
        // } else {
             //   JOptionPane.showMessageDialog(null, "La auditoría con nombre "+empresa+" no existe");
  //  }
         //  } catch (SQLException e) {
          //  e.printStackTrace();
       // }
    }//GEN-LAST:event_btnGuiaActionPerformed

    private void fieldCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(audit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(audit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(audit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(audit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new audit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu anexosENS;
    private javax.swing.JMenu articulosENS;
    private javax.swing.JMenuItem articulosENS2;
    private javax.swing.JButton btnGuia;
    private javax.swing.JButton btnVolver;
    private javax.swing.JTextField fieldAuditor;
    private javax.swing.JTextField fieldCategoria;
    private javax.swing.JTextArea fieldDescripcion;
    private javax.swing.JTextField fieldEmpresa;
    private javax.swing.JTextField fieldID;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelAuditor;
    private javax.swing.JLabel labelDescripcion;
    private javax.swing.JLabel labelEmpresa;
    private javax.swing.JLabel labelID;
    private javax.swing.JMenuItem marcoOperacional;
    private javax.swing.JMenuItem marcoOrganizativo;
    private javax.swing.JMenuItem medidasProteccion;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
